<?php

/**
 * Create a custom search form.
 */
function thu_custom_search_form_alter(&$form, &$form_state, $form_id) {

  global $theme;
  if ($form_id == 'search_block_form' AND $theme == 'dan_thuraya') {
    $form['search_block_form']['#attributes']['placeholder'] = t('What are you looking for?');
    $form['search_block_form']['#attributes']['class'] = array('search-input');
    $form['actions']['submit']['#attributes']['class'] = array('wi-icon', ' wi-icon-search');
    $form['search_block_form']['#theme_wrappers'] = array();

    $form['#theme'] = array('dan_thuraya_custom_search_theme');
    //$form['#submit'][] = 'thu_custom_search_form_user_login_alter';
  }

  if($form_id == 'search_form' && $_GET['q'] != 'search') {
    unset($form['basic']);
    unset($form['advanced']);
  }

}

/**
 * Hook form alter - redirect page search thuraya.com
 * @param type $form
 */
function thu_custom_search_form_user_login_alter($form, &$form_state) {
  $form_state['redirect'] = 'http://thuraya.com/'.$form_state['redirect'];
}

/**
 * Hook theme
 * @return array
 */
function thu_custom_search_theme($existing, $type, $theme, $path) {
  $items = array(
      'dan_thuraya_custom_search_theme' => array(
          'template' => 'dan_thuraya_custom_search_theme',
           'render element' => 'form',
      ),
  );
  return $items;
}
