<?php

/**
 * Implement of hook_info()
 * @return type
 */
function thu_store_location_m2m_block_info()
{
  return array(
    'footer_store_location_m2m' => array(
      'info' => 'Thuraya Manage Store Location M2M'
    ),    
  );
  
}

/**
 * Implement hook_block_view()
 * @param type $delta
 */
function thu_store_location_m2m_block_view($delta)
{
  
  $block = array();
  switch ($delta) {

    case 'footer_store_location_m2m':
      $block['content'] = array('#markup' => '&nbsp;');
      break;
  }
  $block['subject'] = '';
  return $block;
}

/**
 * Hook theme
 * @return array
 */
function thu_store_location_m2m_theme() {
  $themes = array(
      'thu_store_location_m2m' => array(
          'template' => 'thu_store_location_m2m',
      ),
  );
  return $themes;
}
