<?php

define('THU_FEEDS_TWEET_API', 'https://api.twitter.com/1.1/statuses/user_timeline.json');
define('THU_FEEDS_DEFAULT_HASHTAG', '#thuraya');
define('THU_FEEDS_DEFAULT_ACC_TWITTER', 'ThurayaTelecom');
define('THU_FEEDS_TYPE_SOCIAL', 'social_feeds');
define('THU_FEEDS_LIMIT_TITLE', 40);

$library_path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'thu_social_feed') . '/class_get_feed.php';
require_once $library_path;

/**
 * Implements hook_menu().
 */
function thu_social_feed_menu() {
  $items['admin/config/social_feed'] = array(
    'title' => 'Social Feed',
    'description' => 'Configurate value to manage Social Feed content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('social_feed_admin'),
    'access arguments' => array('administer'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_admin().
 */
function social_feed_admin() {
  $form['field_tabs'] = array(
    '#type' => 'vertical_tabs',
  );
  $form['setting'] = array(
    '#type' => 'fieldset',
    '#title' => t('Twitter Settings'),
    '#group' => 'field_tabs',
  );


  $form['setting']['account_twitter'] = array(
    '#type' => 'textfield',
    '#title' => t('Account name'),
    '#default_value' => variable_get('social_feed_account_twitter', THU_FEEDS_DEFAULT_ACC_TWITTER),
  );
  /*$form['setting']['hashtags'] = array(
    '#type' => 'textfield',
    '#title' => t('Hashtags'),
    '#description' => t('Note: You can add multiple value and separate by comma. EX: #tag1,#tag2,#tag3, ...'),
    '#default_value' => variable_get('social_feed_hashtags', '#thuraya'),
  );*/
  $form['setting']['access_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Access token'),
    '#default_value' => variable_get('social_feed_access_token'),
  );

  $form['setting']['access_token_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('Access token secret'),
    '#default_value' => variable_get('social_feed_access_token_secret'),
  );

  $form['setting']['consumer_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Consumer key'),
    '#default_value' => variable_get('social_feed_consumer_key'),
  );

  $form['setting']['consumer_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('Consumer secret'),
    '#default_value' => variable_get('social_feed_consumer_secret'),
  );
  /*$form['setting']["request_uri"] = array(
    '#type' => 'textfield',
    '#title' => t('Request URI'),
    '#default_value' => variable_get('social_feed_request_uri', THU_FEEDS_TWEET_API),
  );*/

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  $form['actions']['getfeeds'] = array(
    '#type' => 'button',
    '#value' => t('Get Twitter Feeds'),
    '#executes_submit_callback' => TRUE,
    '#name' => 'op_get_feeds',
  );

  return $form;
}

/**
 * Implements hook_admin_submit().
 */
function social_feed_admin_submit() {
  if (isset($_REQUEST["op_get_feeds"])) { // action get feed
    $get_feeds = new Thu_Social_Get_Feed();
    $feeds = $get_feeds->get_twitter_feed();
    $get_feeds->save_feeds($feeds);

    drupal_set_message(t('Get Feeds successful'));
  }
  else {  // action save settings
    variable_set('social_feed_account_twitter', $_REQUEST['account_twitter']);
    variable_set('social_feed_hashtags', $_REQUEST['hashtags']);
    variable_set('social_feed_access_token', $_REQUEST['access_token']);
    variable_set('social_feed_access_token_secret', $_REQUEST['access_token_secret']);
    variable_set('social_feed_consumer_key', $_REQUEST['consumer_key']);
    variable_set('social_feed_consumer_secret', $_REQUEST['consumer_secret']);
    variable_set('social_feed_request_uri', $_REQUEST['request_uri']);

    drupal_set_message(t('Save data successful'));
  }
}
