<?php

/**
 * hook_menu().
 */
function v2_social_networks_menu() {

  $items = array();

$items['admin/config/user-interface/social-networks'] = array(
  'title' => 'Manage social networks sharing providers',
  'description' => 'Configure the social networks allowed per language',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('v2_social_networks_manage'),
  'access arguments' => array('access administration pages'),
  'type' => MENU_NORMAL_ITEM,
);

  return $items;
}

/**
 * Call function manager form.
 */
function v2_social_networks_manage($form, &$form_state) {

  $settings_language = mumm_helpers_get_settings_language();

  if (!$form_state['rebuild']) {
    mummm_helpers_set_language_warning_message($settings_language);
  }

  $settings_links = mumm_helpers_settings_language_switcher();
  $form['settings_links'] = array(
    '#markup' => $settings_links
  );
  $form['lang'] = array(
    '#type' => 'hidden',
    '#value' => $settings_language,
  );

  $form['social_networks'] = array(
    '#type' => 'fieldset',
    '#title' => t('Social networks'),
    '#collapsible' => TRUE,
  );

  $options = array(
    'facebook' => t('Facebook'),
    'twitter' => t('Twitter'),
  );

  $form['social_networks']['social_networks_sharing_' . $settings_language] = array(
    '#type' => 'checkboxes',
    '#title' => t('Manage social networks sharing providers'),
    '#options' => $options,
    '#default_value' => variable_get('social_networks_sharing_' . $settings_language, ''),
    '#description' => t('Select the Social networks to enable for the selected language.'),
  );

  return system_settings_form($form);
}
